import React from "react";
import {
  History,
  Calendar,
  ChefHat,
  Leaf,
  Eye,
  ArrowRight,
  Sparkles
} from "lucide-react";
import { RecipeHistoryItem, Recipe, ActiveTab } from "../types";

interface HistoryViewProps {
  history: RecipeHistoryItem[];
  onSelectRecipe: (recipe: Recipe) => void;
  setActiveTab: (tab: ActiveTab) => void;
}

export const HistoryView: React.FC<HistoryViewProps> = ({
  history,
  onSelectRecipe,
  setActiveTab
}) => {
  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-12">
      <div>
        <h2 className="text-xl sm:text-2xl font-bold text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
          <span>Recipe Generation History</span>
          <span className="text-xs px-2.5 py-0.5 rounded-full bg-blue-100 dark:bg-blue-950/60 text-blue-700 dark:text-blue-300 font-bold">
            {history.length} records
          </span>
        </h2>
        <p className="text-xs sm:text-sm text-zinc-500 dark:text-zinc-400 mt-0.5">
          Review previous recipes generated by Chef AI and see food items saved
        </p>
      </div>

      {history.length === 0 ? (
        <div className="py-16 text-center bg-white dark:bg-zinc-900 rounded-3xl border border-zinc-200 dark:border-zinc-800 p-6">
          <div className="w-14 h-14 rounded-2xl bg-blue-50 dark:bg-blue-950/40 text-blue-500 flex items-center justify-center mx-auto mb-3">
            <History className="w-7 h-7" />
          </div>
          <h3 className="text-base font-bold text-zinc-800 dark:text-zinc-200 mb-1">
            No recipe history yet
          </h3>
          <p className="text-xs text-zinc-500 max-w-sm mx-auto mb-5">
            Every time Chef AI generates recipes for your leftovers, they'll be safely recorded here in Firestore.
          </p>
          <button
            onClick={() => setActiveTab("chef")}
            className="px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold shadow-xs transition-colors inline-flex items-center gap-2"
          >
            <ChefHat className="w-4 h-4" />
            <span>Generate Your First Recipe</span>
          </button>
        </div>
      ) : (
        <div className="space-y-3">
          {history.map((item) => (
            <div
              key={item.id}
              className="bg-white dark:bg-zinc-900 rounded-2xl border border-zinc-200 dark:border-zinc-800 p-4 sm:p-5 shadow-xs hover:border-emerald-300 dark:hover:border-emerald-800 transition-colors flex flex-col sm:flex-row sm:items-center justify-between gap-4"
            >
              <div className="space-y-1.5 flex-1 min-w-0">
                <div className="flex items-center gap-2 text-xs text-zinc-400">
                  <Calendar className="w-3.5 h-3.5" />
                  <span>{item.date}</span>
                  <span>•</span>
                  <span className="font-medium text-emerald-600 dark:text-emerald-400">
                    {item.leftoverUtilizationScore}% Leftover Utilization
                  </span>
                </div>

                <h3 className="text-base font-bold text-zinc-900 dark:text-zinc-100 truncate">
                  {item.recipeTitle}
                </h3>

                <div className="flex items-center gap-1.5 flex-wrap">
                  <span className="text-[11px] text-zinc-500 font-medium">
                    Ingredients rescued:
                  </span>
                  {item.ingredientsUsed?.slice(0, 5).map((ing, idx) => (
                    <span
                      key={idx}
                      className="text-[11px] px-2 py-0.5 rounded-md bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 font-medium"
                    >
                      {ing}
                    </span>
                  ))}
                  {item.ingredientsUsed?.length > 5 && (
                    <span className="text-[11px] text-zinc-400">
                      +{item.ingredientsUsed.length - 5} more
                    </span>
                  )}
                </div>
              </div>

              <div className="shrink-0 flex items-center gap-3">
                <button
                  type="button"
                  onClick={() => onSelectRecipe(item.recipe)}
                  className="px-4 py-2 rounded-xl bg-zinc-100 hover:bg-emerald-600 hover:text-white dark:bg-zinc-800 dark:hover:bg-emerald-600 text-zinc-800 dark:text-zinc-200 text-xs font-semibold transition-all flex items-center gap-1.5 shadow-2xs"
                >
                  <Eye className="w-3.5 h-3.5" />
                  <span>Reopen Recipe</span>
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
